source 'http://rubygems.org'
ruby '2.1.1'

gem 'sinatra'
gem 'haml'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'bcrypt'
gem 'shotgun'
gem 'rack-flash3', :git => "git://github.com/treeder/rack-flash.git"
